export const FNVTW= {
    "Symbol": "FNVTW",
    "AssetType": "Common Stock",
    "Name": "Finnovate Acquisition Corp. Warrants",
    "Description": "None",
    "CIK": "1857855",
    "Exchange": "NASDAQ",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "REAL ESTATE & CONSTRUCTION",
    "Industry": "BLANK CHECKS",
    "Address": "1007 N ORANGE ST. 10TH FLOOR, WILMINGTON, DE, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2023-09-30",
    "MarketCapitalization": "None",
    "EBITDA": "None",
    "PERatio": "None",
    "PEGRatio": "None",
    "BookValue": "0.004",
    "DividendPerShare": "None",
    "DividendYield": "0",
    "EPS": "None",
    "RevenuePerShareTTM": "0",
    "ProfitMargin": "0",
    "OperatingMarginTTM": "0",
    "ReturnOnAssetsTTM": "0",
    "ReturnOnEquityTTM": "0",
    "RevenueTTM": "0",
    "GrossProfitTTM": "0",
    "DilutedEPSTTM": "0",
    "QuarterlyEarningsGrowthYOY": "-0.971",
    "QuarterlyRevenueGrowthYOY": "0",
    "AnalystTargetPrice": "None",
    "TrailingPE": "-",
    "ForwardPE": "-",
    "PriceToSalesRatioTTM": "-",
    "PriceToBookRatio": "-",
    "EVToRevenue": "-",
    "EVToEBITDA": "-",
    "Beta": "0.007",
    "52WeekHigh": "0.101",
    "52WeekLow": "0.0062",
    "50DayMovingAverage": "0",
    "200DayMovingAverage": "0",
    "SharesOutstanding": "0",
    "DividendDate": "None",
    "ExDividendDate": "None"
}